[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_renter = "UdJoMb9zUSkAysoSnuxJB2x5k8bn8AqgsS1BaEqTroE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anhtuanpc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
